#!/usr/bin/env bash

ln -s ~/dotfiles/.config ~/.config
ln -s ~/dotfiles/.zshenv ~/.zshenv

if command -v brew &>/dev/null ; then
    brew install neovim fd rg fzf eza node starship lua-language-server gopls uv
    read -p "Install git-credential-manager? Will most likely require sudo. [y/N] " reply
    if [[ "$reply" == [yY] ]]; then
        brew install git-credential-manager
    fi
    rehash
    if command -v uv &>/dev/null ; then
        uv tool install ruff
    fi
    if command -v npm &>/dev/null ; then
        npm install -g typescript-language-server basedpyright
    fi
else
    echo "Don't forget to install neovim, fd, rg, fzf, eza, node, git-credential-manager, lua-language-server, gopls, typescript-language-server, basedpyright, ruff, and uv from your package manager"
fi

# # Install nvm, latest node version, and tree-sitter-cli for installing parsers
# # in neovim.
# echo 'Install nvm?: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash'
# read -q "reply?Proceed? [y/N] "
# if [[ "$reply" == [yY] ]]; then
#     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
#     if command -v nvm &>/dev/null ; then
#         nvm install node
#     fi
#     if command -v npm &>/dev/null ; then
#         npm install -g tree-sitter-cli
#     fi
# fi

echo "Current git name and email: '$(git config --global user.name)' and '$(git config --global user.email)'"
read -p "Change git name and email? [y/N] " reply
echo ''
if [[ "$reply" == [yY] ]]; then
    echo ''
    read -p "git name: " reply?
    echo ''
    git config --global user.name "$reply"
    read -p "git email: " reply?
    echo ''
    git config --global user.email "$reply"
fi

read -p "Define ANDROID_HOME and add to path? [y/N] " reply
echo ''
if [[ "$reply" == [yY] ]]; then
    perl -i -pe 's/(android_installed=)false/$1true/' ./.config/zsh/.zprofile
fi

read -p "Update USER and HOST for prompt.zsh? [y/N] " reply
echo ''
if [[ "$reply" == [yY] ]]; then
    perl -i -pe "s/substitute_this_with_USER/${USER}/" ./.config/zsh/prompt.zsh
    perl -i -pe "s/substitute_this_with_HOST/${HOST}/" ./.config/zsh/prompt.zsh
fi
