#!/usr/bin/env bash

ln -s ~/dotfiles/.config .config
ln -s ~/dotfiles/.zshenv .zshenv

if command -v brew &>/dev/null ; then
    brew install neovim fd rg fzf eza node starship git-credential-manager lua-language-server gopls typescript-language-server basedpyright ruff
else
    echo "Don't forget to install neovim, fd, rg, fzf, eza, node, git-credential-manager, lua-language-server, gopls, typescript-language-server, basedpyright, and ruff from your package manager"
fi

# # Install nvm, latest node version, and tree-sitter-cli for installing parsers
# # in neovim.
# echo 'Install nvm?: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash'
# read -q "reply?Proceed? [y/N] "
# if [[ "$reply" == [yY] ]]; then
#     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
#     if command -v nvm &>/dev/null ; then
#         nvm install node
#     fi
#     if command -v npm &>/dev/null ; then
#         npm install -g tree-sitter-cli
#     fi
# fi

read -q "reply?Change git name and email? [y/N] "
if [[ "$reply" == [yY] ]]; then
    echo ''
    read "reply?git name: "
    git config --global user.name "$reply"
    read "reply?git email: "
    git config --global user.email "$reply"
fi
