#!/usr/bin/env bash

ln -s ~/dotfiles/.config .config
ln -s ~/dotfiles/.zshenv .zshenv

os_kernel="$OSTYPE"
if [[ "${os_kernel}" == darwin* ]] && command -v brew &>/dev/null ; then
    brew install neovim fd rg fzf eza
else
    echo "Don't forget to install neovim, fd, rg, fzf, and eza from your package manager"
fi


# Install nvm, latest node version, and tree-sitter-cli for installing parsers
# in neovim.
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
if command -v nvm &>/dev/null ; then
    nvm install node
fi
if command -v npm &>/dev/null ; then
    npm install -g tree-sitter-cli
fi
