#!/usr/bin/env bash

# If you are on MacOS, add empty string `''` just after `-i`.
sed -i'' 's/substitute_this_with_a_directory//'  ./.config/nvim/lua/ps/plugins/nvim_lspconfig.lua
sed -i'' 's/substitute_this_with_USER//'         ./.config/zsh/prompt.zsh
sed -i'' 's/substitute_this_with_HOST//'         ./.config/zsh/prompt.zsh
sed -i'' 's/soni.pranjals17@gmail.com//'         ./.config/git/config

sed -i'' 's/\(\(java\|android\)_installed=\)false/\1true/' ./.config/zsh/.zprofile
