#!/usr/bin/env bash

# Append '.bkp' to `-i` in order to create a backup of 'file.ext' as
# 'file.ext.bkp'.
perl -i -pe 's/substitute_this_with_a_directory//'  ./.config/nvim/lua/ps/plugins/nvim_lspconfig.lua
perl -i -pe 's/substitute_this_with_USER//'         ./.config/zsh/prompt.zsh
perl -i -pe 's/substitute_this_with_HOST//'         ./.config/zsh/prompt.zsh
perl -i -pe 's/soni.pranjals17@gmail.com//'         ./.config/git/config

perl -i -pe 's/((java|android)_installed=)false/$1true/' ./.config/zsh/.zprofile
