#!/usr/bin/env bash

# If you are on MacOS, add empty string `''` just after `-i`.
gsed -i 's/substitute_this_with_a_directory//' ./.config/nvim/lua/ps/plugins/nvim_lspconfig.lua
gsed -i 's/substitute_this_with_USER//'        ./.config/zsh/prompt.zsh
gsed -i 's/substitute_this_with_HOST//'        ./.config/zsh/prompt.zsh
gsed -i 's/soni.pranjals17@gmail.com//'        ./.config/git/config
